version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:v42
    networks:
      - inception-network
    # volumes:
    #   - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - ./requirements/mariadb/.env

  # wordpress:
  #   depends_on:
  #     - db
  #   image: wordpress:latest
  #   networks:
  #     - inception-network
  #   volumes:
  #     - wordpress:/var/www/html
  #   restart: always
  #   env_file:
  #     - .env

  # nginx:
  #   depends_on:
  #     - wordpress
  #   image: nginx:latest
  #   networks:
  #     - inception-network
  #   ports:
  #     - 443:443
  #   volumes:
  #     - wordpress:/var/www/html
  #   restart: always


networks:
  inception-network:
    name: inception-network

# volumes:
#   mariadb:
#     name: mariadb
#     driver: local
#     driver_opts:
#       type: bind
#       device: /Users/ryhara/tmp/inception/mariadb
#       o: bind
# device VM用にあとで書き換える

  # wordpress:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/ryhara/data/wordpress
  #     o: bind