version: '3'

services:
  mariadb:
    build :
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    container_name: mariadb
    image: mariadb:v42
    networks:
      - inception-network
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - ./requirements/mariadb/.env

  wordpress:
    build :
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:v42
    networks:
      - inception-network
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file:
      - ./requirements/wordpress/.env

  nginx:
    build :
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx:v42
    networks:
      - inception-network
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file:
      - ./requirements/nginx/.env

  adminer:
    build :
      context: .
      dockerfile: ./requirements/bonus/adminer/Dockerfile
    container_name: adminer
    depends_on:
      - mariadb
    image: adminer:v42
    networks:
      - inception-network
    ports:
      - 8080:8080
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

networks:
  inception-network:
    name: inception-network

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      device: ${MARIADB_VOLUME_PATH}
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_VOLUME_PATH}
      o: bind